// Generated by CoffeeScript 1.12.6
var App, SeedApp, Vue, VueRouter, app, router, routes;

Vue = require('vue');

App = require('./App');

VueRouter = require('vue-router');

SeedApp = Vue.extend({});

routes = [
  {
    path: '/',
    component: App
  }
];

Vue.use(VueRouter);

router = new VueRouter({
  routes: routes
});

app = new Vue({
  el: '#app',
  template: '<App/>',
  components: {
    App: App
  }
}, router);

app.$mount('#app');
