// Generated by CoffeeScript 1.12.6
import Vue from 'vue';

import App from './App';

import router from './router';

import store from './store';

Vue.config.productionTip = false;

new Vue({
  el: '#app',
  template: '<App/>',
  components: {
    App: App
  },
  router: router,
  store: store
});
